quiz_proj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('quizes.urls', namespace='quizes')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

quizes/urls.py
from django.urls import path
from .views import (
    cabinet,
    QuizListView,
    loginPage,
    sightup,
    quiz_view,
    quiz_data_view,
    save_quiz_view,
    logoutUser,
    createView,
    documrntationView,
    statistic,
    own_statistic,
    creatQuastion,
    SearchView,
)

app_name = 'quizes'

urlpatterns = [
    path('search/', SearchView, name='SearchForSmt'),#search function
    path('login/cabinet/create/<int:pk>/', creatQuastion, name='creatQuastion'),# get pk
    path('login/cabinet/ownstatic/', own_statistic, name='own_statistic'),# own stat page
    path('login/cabinet/statistic/', statistic, name='statistic'),# stat page
    path('documentation/', documrntationView, name='doc'),# help page
    path('login/cabinet/create/', createView, name="createView"),# create quiz
    path('login/', loginPage, name='log-in-view'),# log in url
    path("sightup/", sightup, name="sightup-view"),# sight up url
    path('login/cabinet/', cabinet, name='cabinet-view'),# account url
    path("logout/", logoutUser, name="logoutUser-vew"),# log out function
    path('', QuizListView.as_view(), name='main-view'),# main page
    path('<pk>/', quiz_view, name='quiz-view'),# get pk
    path('<pk>/save/', save_quiz_view, name='save-view'),#save function
    path('<pk>/data/', quiz_data_view, name='quiz-data-view'),# get data
]

quizes/models.py
from django.db import models
import random



class Quiz(models.Model): # Quiz model
    
    DIFF_CHOICES = ( # options
    ('easy', 'easy'),
    ('medium', 'medium'),
    ('hard', 'hard'),
    )
    
    name = models.CharField(max_length=120)#title
    topic = models.CharField(max_length=120)#what is this thimg about
    number_of_questions = models.IntegerField()#amout of quastins int the quiz
    time = models.IntegerField(help_text="duration of the quiz in minutes")#amout of time given to solve quiz
    required_score_to_pass = models.IntegerField(help_text="required score in %")#required score to pass
    difficluty = models.CharField(max_length=6, choices=DIFF_CHOICES)#uses DIFF_CHOICES

    def __str__(self):
        return f"{self.name}-{self.topic}"

    def get_questions(self):
        questions = list(self.question_set.all())
        random.shuffle(questions)
        return questions[:self.number_of_questions]

    class Meta:
        verbose_name_plural = 'Quizes'

results/models.py
from django.db import models
from django.db.models.deletion import CASCADE
from quizes.models import *
from django.contrib.auth.models import User


class Result(models.Model):# result model
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE, related_name='quiz')#describes wich result it is(quiz)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='results')#describes wich result it is(user)
    score = models.FloatField()#wich score user had
    
    def __str__(self):
        return str(self.pk)
    

quizes/forms.py
from django.forms import ModelForm
from django.forms.widgets import HiddenInput
from .models import Quiz
from questions.models import *

class QuizForm(ModelForm):
    
    class Meta:
        model = Quiz
        fields = '__all__'
        
class AnswearForm(ModelForm):
    class Meta:
        model = Answer
        fields = ['text',
                  'correct',
                  'question',]

class QuastionrForm(ModelForm):
    class Meta:
        model = Question
        fields = ['text',
                  'quiz',]
        # widgets = {'quiz': HiddenInput()}

quizes/views.py
import django
from django.db.models.query import QuerySet
from django.db.models.sql.query import Query
from django.http.request import QueryDict
from django.shortcuts import render, redirect
from .models import Quiz
from django.views.generic import ListView
from django.http import JsonResponse
from questions.models import Question, Answer
from results.models import Result
from django.contrib.auth.forms import UserCreationForm, UserModel
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout, get_user_model
from django.contrib.auth.decorators import login_required
from .forms import *


def documrntationView(request): #Web site help page
    data ={}
    return render(request, 'quizes/documrntationView.html')# render

@login_required(login_url='/login/') #log in needed 
def statistic(request):# all users stat
    users = get_user_model().objects.all()# get all users
    result = Result.objects.all()# get all results models
    result_count = result.count() # count results  
    user_get_id = request.user # get user
    user_id = user_get_id.id # get user id
    user_data =   Result.objects.filter(user__pk=user_id)   # filter requast
    data = {'allusers': users,
            'result_count':result_count,
            'result': user_data
            }    
    return render(request, 'quizes/statistic.html', data)   #render


@login_required(login_url='/login/') #log in needed
def own_statistic(request):# own statistics
    user_get_id = request.user# get user
    user_id = user_get_id.id# get user id
    result = Result.objects.filter(user__pk=user_id)# compare user and pk
    result_count = result.count()# count
    
    
    data = {'result_count' : result_count}
    return render(request, 'quizes/own_statistics.html', data)# render

@login_required(login_url='/login/') #log in needed
def cabinet(request):#own cabinet(accaut)
    data ={}
    return render(request, 'quizes/cabinet.html', data)#render

def loginPage(request):# log in page( page to log in)
    if request.method == "POST":
        username = request.POST.get('username')# requast user
        password = request.POST.get('password')# request users password
        user = authenticate(request, username=username, password=password)# compare with db
        
        if user is not None:
            login(request, user)# make user loged in
            return redirect('/login/cabinet/')# redirect
        else:
            messages.info(request, 'username or pssword is wrong')# retirn erro
    data = {}
    return render(request, 'quizes/login.html', data)# render

@login_required(login_url='/login/') #log in needed
def logoutUser(request):# log out user
    logout(request)# log out
    return redirect('/') # redirect to main page

def sightup(request):# sight up page
    form = UserCreationForm()# use defult django form
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():# make sure all good)
            form.save()# if yes - save
            user = form.cleaned_data.get('username')# get user name
            messages.success(request, 'Acount was created' + user) # return massge
            return redirect('/login/')# redirect
        
        
    data = {'form': form}
    return render(request, 'quizes/sightup.html', data)# render

class QuizListView(ListView):# quiz view
    model = Quiz 
    template_name = 'quizes/main.html'# get template
    
@login_required(login_url='/login/') #log in needed
def quiz_view(request, pk):# show quizes
    quiz = Quiz.objects.get(pk=pk)#get quiz pk
    return render(request, 'quizes/quiz.html', {'obj': quiz})# render
@login_required(login_url='/login/') #log in needed
def quiz_data_view(request, pk):
    quiz = Quiz.objects.get(pk=pk)
    questions = []
    for q in quiz.get_questions():
        answers = []
        for a in q.get_answers():
            answers.append(a.text)
        questions.append({str(q): answers})
    return JsonResponse({
        'data': questions,
        'time': quiz.time,
    })
@login_required(login_url='/login/') #log in needed
def save_quiz_view(request, pk):# save quizes
    if request.is_ajax():
        questions = []
        data = request.POST
        data_ = dict(data.lists())

        data_.pop('csrfmiddlewaretoken')

        for k in data_.keys():
            print('key: ', k)
            question = Question.objects.get(text=k)
            questions.append(question)
        print(questions)

        
        
        user = request.user
        quiz = Quiz.objects.get(pk=pk)

        score = 0
        multiplier = 100 / quiz.number_of_questions
        results = []
        correct_answer = None

        for q in questions:
            a_selected = request.POST.get(q.text)

            if a_selected != "":
                question_answers = Answer.objects.filter(question=q)
                for a in question_answers:
                    if a_selected == a.text:
                        if a.correct:
                            score += 1
                            correct_answer = a.text
                    else:
                        if a.correct:
                            correct_answer = a.text

                results.append({str(q): {'correct_answer': correct_answer, 'answered': a_selected}})
            else:
                results.append({str(q): 'not answered'})
            
        score_ = score * multiplier
        Result.objects.create(quiz=quiz, user=user, score=score_)
        
        if score_ >= quiz.required_score_to_pass:
            return JsonResponse({'passed': True, 'score': score_, 'results': results})
        else:
            return JsonResponse({'passed': False, 'score': score_, 'results': results})
        
@login_required(login_url='/login/') #log in needed    
def createView(request): # create quize(works)
    
    form = QuizForm()
    if request.method == 'POST':
        print('Posting....*', request.POST)
        form = QuizForm(request.POST)
        if form.is_valid():
            form.save()
            
            return redirect(f'/login/cabinet/create/{form.instance.pk}/')
    context ={'form': form}
    return render(request, "quizes/createviews.html", context)# render

@login_required(login_url='/login/') #log in needed 
def creatQuastion(request, pk):# create quastions
    form = AnswearForm()
    form2 = QuastionrForm()
    if request.method == 'POST':
        print('Posting....*', request.POST)
        form = AnswearForm(request.POST)
        form2 = QuastionrForm(request.POST)
        if form.is_valid() and form2.is_valid():
            form.save()
            form2.save()
            return redirect('/login/cabinet/')# render
        
    
    context = {'pk' : pk, 'form': form, 'form2' : form2}
    return render(request, "quizes/created.html", context)

def SearchView(request): # search view
    if request.method == 'POST':
        searched = request.POST['searched']
        quiz = Quiz.objects.filter(name__contains=searched)
        context={
            'searched': searched,
            'quiz': quiz,
                 }
        return render(request, "quizes/search.html", context )# render
    else:
        context={}
        return render(request, "quizes/search.html", context )# render

results/views.py
from django.shortcuts import render

# Create your views here.

quizes/templates/quizes/cabinet.html
<h3><a href='/logout'>log out</a></h3>
<h2> Hello {{request.user}}.</p>
    
<hr>
<div class="h4">Here are quizes/hr quastions wich you can do.<div>
<p>go to <a href='/'> quiez page</a></p>
<p>create a test <a href='/login/cabinet/create/'>here</a></p>
<p>Look for statistic: <a href='/login/cabinet/statistic/'>here</a>
<p> If you have any quastions left: look for <a href='/documentation'>documentation.</a></p>

quizes/templates/quizes/created.html
All good:</br>

<p>
    <form method="POST" action="">
    
        {% csrf_token %}
        For text write down your question, and for Quiz select Quiz wich you have created:
        {{ form2.as_p }}
        {% comment %} <hr>
        For text make an option of answear, one of them must bet marked as true, for question select the corent quastion.</br>
        {{ form.as_p }}
    </br><hr>
        {{ form.as_p }}
    </br><hr>
        {{ form.as_p }}
    </br><hr>
        {{ form.as_p }} {% endcomment %}
        <input type="submit" action="submit">
    </form>
    </p>
<a href='/login/cabinet'>Go back</a>

quizes/templates/quizes/createview.html
<h2>Create a quiz here, then evrythin else</h2>
<p>
<form method="POST" action="">

    {% csrf_token %}
    {{ form }}
    <input type="submit" action="Submit">
</form>
</p>

quizes/templates/quizes/createviews.html
<h2>Create a quiz here, then evrythin else</h2>
<p>
<form method="POST" action="">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" action="Submit">
</form>
</p>

quizes/templates/quizes/documrntationView.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title>documentation</title>
  </head>
  <body>
    <h2>Welcome to the documentation.</h2>
    <div class='nav-bar'>
    
        <li><a href="#login">log in/sight up</a></br>
            <li><a href="#quiz">how to do quzes</a></br>
                <li><a href="#acount">accaunt</a></br>
                    <li><a href="#password">forgot a password?</a></br>
                      <li><a href='#other'>other quastions  </a></br>
        
    </div><hr></br></br></br></br>
    <h2>How to log in/sight up.</h2>
    <div id='login'><p>If you have an acound, just <a href='/login'>log in</a>, if you dont</br>
       have one you can create in <a href='/sightup'>here.</a></p>
        <p> In case if you forgot your password, go <a href='#'>here</a></p>
      </div><hr></br></br></br></br>
      
    <div id='quiz'>
      <h2>How to do quizes?</h2>
      <li>first you need an account</li>
      <li>then log in with this acount</li>
      <li>now you can chouse the test and make it, test are avalibel <a href='/'>here</a></li>
    </div><hr></br></br></br></br>
    
    <div id='acount'>
      <h2>What can you do in account?</h2>
      <p>To acsse acount <a href='login'>log in</a> or <a href='sighup'>sigh up</a>, then you cna got you acount.</br>
        Now you can:</p> 
        <li>solve <a href='/'>quizes</a></li>
        <li>view <a href='/login/cabinet/result'>results<a/>
        <li>Create and eddit <a href='/login/cabinet/'>quizes</a></li>
      </div><hr></br></br></br></br>

      <div id='password'>
        <h2>If you forgot a password?</h2>
          <p>In this case write to this email: bai2016up@gmail.com.</br>
            make sure to write your user name.</p>
          </div><hr></br></br></br></br>
        <div id='other'>
          <h2>IF you have any other quastions:</h2>
          <p>Please if you have any other quastions write to this email: bai2016up@gmail.com.</p>
        </div>

    

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
  </body>
</html>

quizes/templates/quizes/login.html
<!DOCTYPE html>
<html>
    
<head>
	<title>Login</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">


	<style>
		body,
		html {
			margin: 0;
			padding: 0;
			height: 100%;
			background: #7abecc !important;
		}
		.user_card {
			width: 350px;
			margin-top: auto;
			margin-bottom: auto;
			background: #74cfbf;
			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			border-radius: 5px;

		}

		.form_container {
			margin-top: 20px;
		}

		#form-title{
			color: #fff;
			
		}

		.login_btn {
			width: 100%;
			background: #33ccff !important;
			color: white !important;
		}
		.login_btn:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}
		.login_container {
			padding: 0 2rem;
		}
		.input-group-text {
			background: #f7ba5b !important;
			color: white !important;
			border: 0 !important;
			border-radius: 0.25rem 0 0 0.25rem !important;
		}
		.input_user,
		.input_pass:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}

		#messages{
			background-color: grey;
			color: #fff;
			padding: 10px;
			margin-top: 10px;
		}
	</style>

</head>
<body>
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">


					<h3 id="form-title">LOGIN</h3>
				</div>
				<div class="d-flex justify-content-center form_container">
					<form method="POST" action="">
                        {% csrf_token %}
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>
							<input type="text" name="username" placeholder="Username..." class="form-control">
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
								<input type="password" name="password" placeholder="Password..." class="form-control" >
						</div>

							<div class="d-flex justify-content-center mt-3 login_container">
				 				<input class="btn login_btn" type="submit" value="Login">
				   			</div>
					</form>

				</div>
		

			

                    {% for message in messages %}
                        <p id='messages'>{{ messages }}</p>
                    {% endfor %}
				</div>
			</div>
		</div>
	</div>
</body>

</html>

quizes/templates/quizes/main.html
{% extends "base.html" %}
{% load static %}

{% block scripts %}
    <script src="{% static 'quizes/main.js' %}" defer></script> 
{% endblock scripts %}
{% block title %}
home
{% endblock title %}

{% block content %}

<!-- Modal -->
<div class="modal fade" id="quizStartModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Start?</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body" id="modal-body-confirm"></div>
      <div class="modal-footer">
        <button type="button" class="btn btn-danger" data-dismiss="modal">no</button>
        <button type="button" id="start-button" class="btn btn-success">yes</button>
      </div>
    </div>
  </div>
</div>

<div class="h1">Quiz List</div>
<h2> Hello {{request.user}}.</p><h2>Got to your <a href="/login/cabinet/">acount</a>
<hr>
<div class="h4">Here are quizes quastions wich you can do.<div>
<form class='d-flex' method='POST' action="{% url 'quizes:SearchForSmt' %}">
  {% csrf_token %}
  <input class='form-control-label' type='search' plaseholder='Search for' name='searched'>
  <button class='btn btn-primary' type='submit'>submit</button> 
</form>
<div class="worming"><p>Make sure you have an acount, other ways the test will not work</p></div>
<div class="logIn"><p>If you don,t have an acount, sigh up <a href="/sightup">now</a>.</p></div> 
<h3 class='cabinet'>log in to your personal online <a href='login/'>account</a>.</h3>
<p>Look for statistic: <a href='/login/cabinet/statistic/'>here</a>
<h4> If you have any quastions left: look for <a href='documentation'>documentation.</a></h4>
<hr>


{% for obj in object_list %}


    <button
        class="btn btn-link modal-button"
        data-pk="{{obj.pk}}"
        data-quiz="{{obj.name}}"
        data-questions="{{obj.number_of_questions}}"
        data-difficulty="{{obj.difficluty}}"
        data-time="{{obj.time}}"
        data-pass = "{{obj.required_score_to_pass}}"
        data-toggle="modal"
        data-target="#quizStartModal">
        {{obj.name}}
    </button><br>

{% endfor %}
{% endblock content %}

    

quizes/templates/quizes/own_statistics.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title>statistik</title>
  </head>
  <body>
    <h1>Here is your staticstic</h1>
   <p>amount of test done - {{ result_count }}</p>
   <p>
   {% for i in user_data %}
    <hr>
    <p> Quize -{{ i.quiz }}</p>
    <p> Who - {{ i.user }}</p>
    <p> Score - {{ i.score }}</p>
    {% comment %} <p>Do test again - {{ data.quiz_link }}</p> {% endcomment %}

{% endfor %}</p>
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
  </body>
</html>

quizes/templates/quizes/quiz.html
{% extends "base.html" %}
{% load static %}

{% block scripts %}
    <script src="{% static 'quizes/quiz.js' %}" defer></script> 
{% endblock scripts %}

{% block title %}
{{obj.name}}
{% endblock title %}

{% block content %}

<div class="row">
    <div class="col">
        <b>{{obj.name}}</b>
        <p>score to pass: {{obj.required_score_to_pass}}%</p>
    </div>
    <div class="col text-right" id="timer-box"></div>
</div>

<a href="{% url 'quizes:main-view' %}" class="btn btn-danger">go back</a>

<form id="quiz-form" class="mt-3 mb-3">
    {% csrf_token %}
    <div id="quiz-box"></div>
    <button type="submit" class="btn btn-primary mt-3">save</button>
</form>
<div id="score-box"></div>
<div id="result-box"></div>
{% endblock content %}

quizes/templates/quizes/resultview.html
<h2>Your results:</h2>

{% for data in result %}
    <hr>
    <p> Quize -{{ data.quiz }}</p>
    <p> Who - {{ data.user }}</p>
    <p> Score - {{ data.score }}</p>
    {% comment %} <p>Do test again - {{ data.quiz_link }}</p> {% endcomment %}

{% endfor %}

quizes/templates/quizes/search.html
{% extends "quizes/main.html" %}
{% load static %}
{% block content %}
<h3><a href='/' calss='btn-link modal-button'>go back</a></h3>
    <center>
        
        {% if searched %} 
       <h1>You look for {{ searched }}.</h1>
       <hr></br>

       {% for i in quiz %}
            <h4><a href='/{{ i.id }}' calss='btn-link modal-button'>{{ i.name }}</a></h4><br>
       {% endfor %}
        {% else %}
        <h1>Nothig to search.</h1>
       {% endif %}
    </center>
{% endblock %}

quizes/templates/quizes/sightup.html
<h3>create an acaunt</h3>
<form method="POST" action="">{% csrf_token %}
    {{form.as_p}}
    <input type="submit" name="Create user">
</form>

quizes/templates/quizes/statistic.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

   
  </head>
  <body>
    <h1>List of best users</h2>
      <p>see your statistik <a href='/login/cabinet/ownstatic'>here</a></p>
      <p>see best palyers <a href='#'>here</a></p>
      <hr>
    
    {% for i in allusers %}
    
      <p> user -  {{ i.get_username }}</p>z
      <p> amount of done tests - {{ i.results.count }}
        <hr>
    {% endfor %}

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
  </body>
</html>